artifact_location: /home/mwildanm/fmcg-dynamic-pricing/"http:/forcaster.duckdns.org:5000"/0
creation_time: 1779536888073
experiment_id: '0'
last_update_time: 1779536888073
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
