[theme]
base="dark"
primaryColor="#818CF8"
backgroundColor="#141822"
secondaryBackgroundColor="#1C2132"
textColor="#E2E8F0"
font="sans serif"

[server]
maxUploadSize=5
enableXsrfProtection=true

[browser]
gatherUsageStats=false
